spring:
   datasource:
      username: world_tour
      password: world_tour
      url: jdbc:mysql://localhost:3306/world_tour
      
   jpa:
      hibernate:
         ddl-auto: none
      show-sql: true
      defer-datasource-initialization: true
      
   sql:
      init:
         mode: always